#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
require 'commander/import'
require 'dotenv/load'
require 'net/smtp'
require 'mailfactory'
require 'open-uri'
require './lib/send'

# check if ebook-convert is on the path
# notify the user that the kindle email must be whitelisted

program :name, 'kindle'
program :help, 'Author', 'Plamen Kolev <p.kolev22@gmail.com>'
program :version, '0.1'
program :description, 'Command line tool for sending online articles and books to your kindle device via email. Send an html webpage directly to your kindle withing a second. The tool also enables local mobi, pdf and txt files to be sent.'
program :help, 'Command arguments', 'send'

command :send do |c|
  c.syntax = 'https://en.wikipedia.org/wiki/Kukeri'
  c.description = 'Sends article url or local file to kindle via email'
  c.action do |args, options|
    # validate number of arguments (accepting only 1)
    raise ArgumentError, "More arguments supplied" if args.length != 1
    # check if online article
    puts 
    case args[0]
    when /^http/
      # download resource first
      smtp(args[0], true)
    else
      # do not download
      smtp(args[0], false)
    end
  end
end


